services:
  db:
    image: postgres:17.6
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5433:5432"
    volumes:
      - digital_shelf:/var/lib/postgresql/data
    networks:
      - app_network

  ocr:
    build:
      context: ./ocr
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  frontend:
    build:
      context: .
      dockerfile: ./src/digital_shelf/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - db
      - ollama
    volumes:
      - ./src:/app/src
      - ./src/digital_shelf/.streamlit:/app/.streamlit
    networks:
      - app_network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.digital-shelf.rule=Host(`digital-shelf.vincentvega.ddns.net`)"
      - "traefik.http.routers.digital-shelf.entrypoints=websecure"
      - "traefik.http.routers.digital-shelf.tls.certresolver=lets"
      - "traefik.http.routers.digital-shelf.service=digital-shelf"
      - "traefik.http.services.digital-shelf.loadbalancer.server.port=8501"
      - "traefik.docker.network=proxy"
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - WANDB_PROJECT=${WANDB_PROJECT}
      - WANDB_ENTITY=${WANDB_ENTITY}

  ollama:
    image: ollama/ollama:0.13.0
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    networks:
      - app_network

volumes:
  digital_shelf:
  ollama_data:

networks:
  app_network:
  proxy:
    external: true